import type { PlaylistConfig, PlaylistType } from "./types";

export const PLAYLIST_CONFIGS: Record<PlaylistType, PlaylistConfig> = {
  transport: {
    type: "transport",
    label: "Транспорт",
    subtitle: "Медиаплейлист наземного транспорта",
    locationLabel: "Транспорт",
    categoryLabel: "Категория",
    clientLabel: "Заказчик",
    mediaLabel: "Медиаобъект",
    headerGradient: "from-rose-950 via-red-900 to-rose-900",
    accentColor: "text-amber-300",
    buttonGradient: "from-rose-600 to-red-600",
    dotColor: "bg-amber-400",
    borderColor: "border-rose-100/60",
    iconBg: "bg-white/10",
  },
  mfc: {
    type: "mfc",
    label: "МФЦ",
    subtitle: "Медиаплейлист МФЦ",
    locationLabel: "МФЦ",
    categoryLabel: "Блок",
    clientLabel: "Заказчик",
    mediaLabel: "Название ролика",
    headerGradient: "from-blue-950 via-blue-900 to-blue-950",
    accentColor: "text-sky-300",
    buttonGradient: "from-blue-600 to-blue-700",
    dotColor: "bg-sky-400",
    borderColor: "border-blue-100/60",
    iconBg: "bg-white/10",
  },
  metro: {
    type: "metro",
    label: "Метро",
    subtitle: "Медиаплейлист метро",
    locationLabel: "Станция",
    categoryLabel: "Блок",
    clientLabel: "Заказчик",
    mediaLabel: "Название ролика",
    headerGradient: "from-emerald-950 via-emerald-900 to-emerald-950",
    accentColor: "text-teal-300",
    buttonGradient: "from-emerald-600 to-emerald-700",
    dotColor: "bg-teal-400",
    borderColor: "border-emerald-100/60",
    iconBg: "bg-white/10",
  },
  lift: {
    type: "lift",
    label: "Лифт",
    subtitle: "Медиаплейлист лифтов",
    locationLabel: "НП",
    categoryLabel: "Блок",
    clientLabel: "Заказчик",
    mediaLabel: "Название ролика",
    headerGradient: "from-violet-950 via-purple-900 to-violet-950",
    accentColor: "text-purple-300",
    buttonGradient: "from-violet-600 to-purple-700",
    dotColor: "bg-purple-400",
    borderColor: "border-violet-100/60",
    iconBg: "bg-white/10",
  },
  kd: {
    type: "kd",
    label: "КД",
    subtitle: "Медиаплейлист КД",
    locationLabel: "КД",
    categoryLabel: "Блок",
    clientLabel: "Заказчик",
    mediaLabel: "Название ролика",
    headerGradient: "from-amber-950 via-orange-900 to-amber-950",
    accentColor: "text-orange-300",
    buttonGradient: "from-amber-600 to-orange-600",
    dotColor: "bg-orange-400",
    borderColor: "border-amber-100/60",
    iconBg: "bg-white/10",
  },
};

export const PLAYLIST_TYPES: PlaylistType[] = ["transport", "mfc", "metro", "lift", "kd"];

// Category styles used across all playlist types
export const CATEGORY_STYLES: Record<string, { bg: string; text: string; dot: string }> = {
  "Реклама 1": { bg: "bg-amber-50", text: "text-amber-700", dot: "bg-amber-500" },
  "Реклама 2": { bg: "bg-emerald-50", text: "text-emerald-700", dot: "bg-emerald-500" },
  "Реклама 3": { bg: "bg-blue-50", text: "text-blue-700", dot: "bg-blue-500" },
  "Реклама 4": { bg: "bg-violet-50", text: "text-violet-700", dot: "bg-violet-500" },
  "Сетка реклама": { bg: "bg-rose-50", text: "text-rose-700", dot: "bg-rose-500" },
  "Партнеры": { bg: "bg-stone-50", text: "text-stone-600", dot: "bg-stone-400" },
  "Социальная": { bg: "bg-cyan-50", text: "text-cyan-700", dot: "bg-cyan-500" },
  "Информационная": { bg: "bg-indigo-50", text: "text-indigo-700", dot: "bg-indigo-500" },
};
